import type { Core } from '@strapi/strapi'
import { upsertList } from '../utils'

/**
 * All 82 documented media appearances, transcribed verbatim from the client copy
 * (`Documentation/Pagini/8. Media/Media_Copy.docx` → section 6 "INVENTAR COMPLET — 82 APARIȚII").
 *
 * Grouping in the source doc drives `type`:
 *   TV (22) · PODCAST (39) · PUBLICAȚIE (16) · RADIO (1) · EVENIMENTE (4)
 *
 * `brand` comes from the [brackets] on each row:
 *   "Costin Damasaru" → costin · "Veruvis" → veruvis · "Veruvis Kids" → veruvis-kids
 *
 * `featured` is true only for the 8 hand-picked cards (CONTEXT, all with real YouTube IDs):
 *   34 Măruță · 61 Mihai Morar · 25 Mihai Morar 2 · 8 Reportaj ProTV @GoTech World ·
 *   65 ProTV Vorbește Lumea · 32 TVR Eu Pot · 43 TEDx Constanța · 3 Mind Architect.
 *
 * `isMagazine` is true only for the reviste present in the 82-row inventory:
 *   60 Revista Psychologies · 75 Forbes CEE Forum 2023 · 76 Forbes 24 pentru 2024.
 *   (CARIERE, HR Manager, Biz from copy §5.4 are NOT among the 82 documented rows.)
 *
 * Upsert key is `url` — each row's URL is unique and verifiable.
 */
export async function seedPressMentions(strapi: Core.Strapi): Promise<void> {
  const items = [
    // ============================================================
    // TV (22 apariții)
    // ============================================================
    {
      title: 'Ilinca Vandici & Teo Trandafir',
      outlet: 'Kanal D',
      url: 'https://www.youtube.com/watch?v=YDEsrnrRmyQ',
      type: 'tv',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Reportaj ProTV @GoTech World — min. 20',
      outlet: 'Pro TV',
      url: 'https://www.youtube.com/watch?v=KZjbRKZY9GY',
      type: 'tv',
      brand: 'veruvis',
      isMagazine: false,
      featured: true,
    },
    {
      title: 'Agrostrategia',
      outlet: 'TVR 1',
      url: 'https://www.youtube.com/watch?v=mPzQkUmzXIM',
      type: 'tv',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'POVESTI DE POVESTE cu Ani Cășărică',
      outlet: 'Povești de Poveste',
      url: 'https://www.youtube.com/watch?v=VntgHrPk5Bk',
      type: 'tv',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Curiozitate',
      outlet: 'Canal 33',
      url: 'https://www.youtube.com/watch?v=V5pZyJtQVn4',
      type: 'tv',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'TVR INFO',
      outlet: 'TVR',
      url: 'https://www.youtube.com/watch?app=desktop&v=TV7BIFyC_Zo',
      type: 'tv',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Metropola TV',
      outlet: 'Metropola TV',
      url: 'https://www.youtube.com/watch?v=aCmCL09BvX4',
      type: 'tv',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Eu Pot',
      outlet: 'TVR',
      url: 'https://www.youtube.com/watch?v=x6pEY7HWSNU',
      type: 'tv',
      brand: 'costin',
      isMagazine: false,
      featured: true,
    },
    {
      title: 'Punctul Critic',
      outlet: 'TVR 1',
      url: 'https://www.youtube.com/watch?v=RjoTOuHAQd4&list=PLgwhKg2ry2ehfzhvGQBVVA9Of_IqL5thu&index=9',
      type: 'tv',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'WOW News',
      outlet: 'WOW News',
      url: 'https://www.youtube.com/watch?v=anlytnwXIbQ&t=144s',
      type: 'tv',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Adevărul',
      outlet: 'Adevărul',
      url: 'https://www.youtube.com/watch?v=7FytnIlt5uU&list=PLgwhKg2ry2ehfzhvGQBVVA9Of_IqL5thu&index=7',
      type: 'tv',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Canal 33',
      outlet: 'Canal 33',
      url: 'https://www.youtube.com/watch?v=3-rYmIo0qNU&list=PLgwhKg2ry2ehfzhvGQBVVA9Of_IqL5thu&index=6',
      type: 'tv',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Observator',
      outlet: 'Antena 1',
      url: 'https://www.youtube.com/watch?v=wHBcQGJm4B4',
      type: 'tv',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'MediCool',
      outlet: 'MediCool',
      url: 'https://www.youtube.com/watch?v=TrKet3waHn4',
      type: 'tv',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Etno TV',
      outlet: 'Etno TV',
      url: 'https://www.youtube.com/watch?v=K_-KWd_XJdY&list=PLnWPfRFizC-eqgDf8Fsk6IC-IztwDXjN5&index=17',
      type: 'tv',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Un doctor pentru dumneavoastră',
      outlet: 'TVR Internațional',
      url: 'https://www.youtube.com/watch?v=X_5NKIO1fuI',
      type: 'tv',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'ProTV',
      outlet: 'Pro TV',
      url: 'https://www.youtube.com/watch?v=ugXgeosWFZw',
      type: 'tv',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Vorbește Lumea',
      outlet: 'Pro TV',
      url: 'https://www.youtube.com/watch?v=Jr37W7oaBoc',
      type: 'tv',
      brand: 'veruvis',
      isMagazine: false,
      featured: true,
    },
    {
      title: 'Canal 33',
      outlet: 'Canal 33',
      url: 'https://www.youtube.com/watch?v=pWda3yYKzcY',
      type: 'tv',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: "D'Economic News cu Alex Vlădescu",
      outlet: 'DCNews TV',
      url: 'https://www.dcnews.ro/psihiologul-roman-care-face-2-milioane-de-euro-pe-an-antrenand-neuronii-antreprenorilor-si-sportivilor-vine-in-studioul-dc-news-tv_935820.html',
      type: 'tv',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Cum să ne vindecăm de toxicitatea din viața noastră',
      outlet: 'Adevărul Live',
      url: 'https://adevarul.ro/adevarul-live/cum-sa-ne-vindecam-de-toxicitatea-din-viata-2323386.html',
      type: 'tv',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Tag mențiuni',
      outlet: 'Antena 3 CNN',
      url: 'https://www.antena3.ro/tag/costin-damasaru-367829.html',
      type: 'tv',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },

    // ============================================================
    // PODCAST (39 apariții)
    // ============================================================
    {
      title: 'Aparența și Esența cu Bogdan Vlădău',
      outlet: 'Aparența și Esența',
      url: 'https://www.youtube.com/watch?v=oVOzEq-Ifvw',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Mind Architect — Paul Olteanu',
      outlet: 'Mind Architect',
      url: 'https://www.youtube.com/watch?v=3oqoQzbkxvM',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: true,
    },
    {
      title: 'Cafea cu visuri — Oana Andoni',
      outlet: 'Cafea cu visuri',
      url: 'https://www.youtube.com/watch?v=GDdAuBvCbS0',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Jorje',
      outlet: 'Jorje',
      url: 'https://www.youtube.com/watch?v=AKixW6npsdw&list=PL5G773Vk7KfY-GMt6eQguB9nioCEWJe-t&index=4',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'NeuroXplorers by ItsyBitsy',
      outlet: 'ItsyBitsy',
      url: 'https://www.youtube.com/playlist?list=PL-myXD70ZZ-6lOy-MTeL54keNHFBeb0W6',
      type: 'podcast',
      brand: 'veruvis-kids',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Podcast cu Sens By Natasha #30',
      outlet: 'Podcast cu Sens',
      url: 'https://www.youtube.com/watch?v=sXz02Tzs6lg',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Oreste Teodorescu',
      outlet: 'Oreste Teodorescu',
      url: 'https://www.youtube.com/watch?v=bFajMr-XjrE',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Celebru și Părinte cu Marius Gheorghiu — Partea II',
      outlet: 'Celebru și Părinte',
      url: 'https://www.youtube.com/watch?v=nYQXmi-Kzc4',
      type: 'podcast',
      brand: 'veruvis-kids',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Tați care iubesc',
      outlet: 'Tați care iubesc',
      url: 'https://www.youtube.com/watch?v=JoJQqaKoWd0',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Silviu Rotariu',
      outlet: 'Silviu Rotariu',
      url: 'https://www.youtube.com/watch?v=IW2hd_XO52g',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Celebru și Părinte cu Marius Gheorghiu — Partea I',
      outlet: 'Celebru și Părinte',
      url: 'https://www.youtube.com/watch?v=JlC9C1M-NAw',
      type: 'podcast',
      brand: 'veruvis-kids',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Universul Parental',
      outlet: 'Universul Parental',
      url: 'https://www.youtube.com/watch?v=eAGY9d69hy8',
      type: 'podcast',
      brand: 'veruvis-kids',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Fabius Antal',
      outlet: 'Fabius Antal',
      url: 'https://www.youtube.com/watch?v=dadUhvtoGBI',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Mandachi',
      outlet: 'Mandachi',
      url: 'https://www.youtube.com/watch?v=A-ohwaIOJYY',
      type: 'podcast',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Autism Voice',
      outlet: 'Autism Voice',
      url: 'https://www.youtube.com/watch?v=QzoVcVAFxwo',
      type: 'podcast',
      brand: 'veruvis-kids',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Mihai Morar 2',
      outlet: 'Fain & Simplu',
      url: 'https://www.youtube.com/watch?v=NZfe1mDl8uU',
      type: 'podcast',
      brand: 'veruvis',
      isMagazine: false,
      featured: true,
    },
    {
      title: 'Doctor Cezar',
      outlet: 'Doctor Cezar',
      url: 'https://www.youtube.com/watch?v=XNAmkiKIJmU',
      type: 'podcast',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Jorje',
      outlet: 'Jorje',
      url: 'https://www.youtube.com/watch?v=wvsbRh2a1RM',
      type: 'podcast',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Ela Crăciun',
      outlet: 'Ela Crăciun',
      url: 'https://www.youtube.com/watch?v=cwhB3_WJxag',
      type: 'podcast',
      brand: 'veruvis-kids',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Radu Constantin',
      outlet: 'Radu Constantin',
      url: 'https://www.youtube.com/watch?v=UafVob7xfYI',
      type: 'podcast',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'TVBreak',
      outlet: 'TVBreak',
      url: 'https://www.youtube.com/watch?v=pLlq8fNC8_c',
      type: 'podcast',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Cristian Stan',
      outlet: 'Cristian Stan',
      url: 'https://youtu.be/ZKV5Oia6rLo?si=eEXG3aKECHhA5xjv',
      type: 'podcast',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Măruță',
      outlet: 'Acasă la Măruță',
      url: 'https://www.youtube.com/watch?v=aZip-MfPhNw',
      type: 'podcast',
      brand: 'veruvis',
      isMagazine: false,
      featured: true,
    },
    {
      title: 'Mirela Retegan',
      outlet: 'Mirela Retegan',
      url: 'https://www.youtube.com/watch?v=2wiMaI5t_DM&t=126s',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Mami, crește-mă frumos!',
      outlet: 'Mami, crește-mă frumos!',
      url: 'https://www.youtube.com/watch?v=_pZTX-dfGeA',
      type: 'podcast',
      brand: 'veruvis-kids',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Excelent de bine',
      outlet: 'Excelent de bine',
      url: 'https://www.youtube.com/watch?v=M087P8iiBE8',
      type: 'podcast',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Start-up Business',
      outlet: 'Start-up Business',
      url: 'https://www.youtube.com/watch?v=W4niGCvM4SA&t=48s',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Creștem Mari',
      outlet: 'Creștem Mari',
      url: 'https://www.youtube.com/watch?v=p8rMNA0Q-1c',
      type: 'podcast',
      brand: 'veruvis-kids',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Florentina Fântânaru — ZUnivers Podcasts',
      outlet: 'ZUnivers Podcasts',
      url: 'https://www.youtube.com/watch?v=lmC7qxt_AJ0&t=405s',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Damian Drăghici',
      outlet: 'Damian Drăghici',
      url: 'https://www.youtube.com/watch?v=eVe5UU7Hdi4',
      type: 'podcast',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Hacking Work',
      outlet: 'Hacking Work',
      url: 'https://www.youtube.com/watch?v=xHklJprCM3A&t=103s',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Ilinca Vandici',
      outlet: 'Ilinca Vandici',
      url: 'https://www.youtube.com/watch?v=lsJ-w6mrBAo',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Armânamea Media',
      outlet: 'Armânamea Media',
      url: 'https://www.youtube.com/watch?v=RwYRkr4oWF4',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'theXclusive',
      outlet: 'theXclusive',
      url: 'https://www.youtube.com/watch?v=4BmkE9jbZDM',
      type: 'podcast',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Calea de Mijloc',
      outlet: 'Calea de Mijloc',
      url: 'https://www.youtube.com/watch?v=e9C2JoJsD0E',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Mihai Morar',
      outlet: 'Fain & Simplu',
      url: 'https://www.youtube.com/watch?v=GBUST4tXG6k',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: true,
    },
    {
      title: 'Mădălin Ionescu',
      outlet: 'Mădălin Ionescu',
      url: 'https://www.youtube.com/watch?v=jL_uTnM3qAA',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Medika TV',
      outlet: 'Medika TV',
      url: 'https://www.youtube.com/watch?v=oRafZd2oZGA',
      type: 'podcast',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'BiziLiveTV — UpGrade',
      outlet: 'BiziLiveTV',
      url: 'https://www.youtube.com/watch?v=vX635ejwjgU',
      type: 'podcast',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },

    // ============================================================
    // PUBLICAȚIE (16 apariții)
    // ============================================================
    {
      title: 'Editura Herald',
      outlet: 'Editura Herald',
      url: 'https://www.youtube.com/watch?v=bFtrz0j0utE',
      type: 'publicatie',
      brand: 'veruvis-kids',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Editura Herald',
      outlet: 'Editura Herald',
      url: 'https://www.youtube.com/watch?v=f5pQjVGAYak',
      type: 'publicatie',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Unica',
      outlet: 'Unica',
      url: 'https://www.youtube.com/watch?v=A6UWoEOjqkQ',
      type: 'publicatie',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Revista Psychologies',
      outlet: 'Psychologies',
      url: 'https://www.youtube.com/watch?v=fakcgSwBevY',
      type: 'publicatie',
      brand: 'costin',
      isMagazine: true,
      featured: false,
    },
    {
      title: 'Cum ne ajută Brain Mapping–BCI să ne optimizăm creierul',
      outlet: 'HotNews',
      url: 'https://hotnews.ro/dr-psih-drd-costin-damasaru-fondatorul-veruvis-cum-ne-poate-ajuta-tehnologia-brain-mapping-brain-computer-interface-sa-ne-optimizam-creierul-17675',
      type: 'publicatie',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Interviu antreprenor Veruvis',
      outlet: 'Business Magazin (ZF)',
      url: 'https://www.zf.ro/eveniment/business-magazin-costin-damasaru-fondator-veruvis-centrul-de-22213489',
      type: 'publicatie',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Neuro Performance Enhancement Center',
      outlet: 'ZF Live',
      url: 'https://www.zf.ro/profesii/zf-live-2020-costin-damasaru-neuro-performance-enhancement-center-18923510',
      type: 'publicatie',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Tehnologii pentru optimizarea creierului',
      outlet: 'Ziarul Financiar (Business Hi-Tech)',
      url: 'https://www.zf.ro/business-hi-tech/costin-damasaru-fondator-veruvis-tehnologii-optimizarea-creierului-22115635',
      type: 'publicatie',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Forbes CEE Forum 2023 — Conceptul de AI se poate numi mai bine inteligență non-umană',
      outlet: 'Forbes România',
      url: 'https://www.forbes.ro/forbes-cee-forum-2023-costin-damasaru-fondator-ceo-veruvis-din-punctul-meu-de-vedere-conceptul-de-ai-se-poate-numi-mai-bine-inteligenta-non-umana-357168',
      type: 'publicatie',
      brand: 'veruvis',
      isMagazine: true,
      featured: false,
    },
    {
      title: '24 pentru 2024 — Viitorul nu este al inteligenței artificiale, ci al creierului uman optimizat',
      outlet: 'Forbes România',
      url: 'https://www.forbes.ro/24-pentru-2024-costin-damasaru-fondator-veruvis-viitorul-nu-este-al-inteligentei-artificiale-ci-al-creierului-uman-optimizat-377242',
      type: 'publicatie',
      brand: 'costin',
      // Forbes appears once as a distinct magazine cover (Z4b shows 5 outlets);
      // the CEE Forum 2023 row above carries the Forbes masthead.
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Drumul către performanță prin tehnologie — Cover story ediția print nr. 286',
      outlet: 'Revista CARIERE',
      url: 'https://revistacariere.ro/inspiratie/costin-damasaru-drumul-catre-performanta-prin-tehnologie',
      type: 'publicatie',
      brand: 'costin',
      isMagazine: true,
      featured: false,
      excerpt: 'Ediția print nr. 286 · Articolul de deschidere',
    },
    {
      title: 'Resurse umane & Leadership — grupul editorial Cariere & HR Manager',
      outlet: 'Revista HR Manager',
      url: 'https://www.youtube.com/@REVISTA.CARIERE',
      type: 'publicatie',
      brand: 'costin',
      isMagazine: true,
      featured: false,
      excerpt: 'Editura Cariere · Resurse umane & Leadership',
    },
    {
      title: 'Metoda inovatoare de antrenament neuronal este utilizată cu succes',
      outlet: 'Revista Biz',
      url: 'https://www.revistabiz.ro/costin-damasaru-veruvis',
      type: 'publicatie',
      brand: 'veruvis',
      isMagazine: true,
      featured: false,
      excerpt: 'Interviu antreprenor',
    },
    {
      title: 'De ce mâncăm fără oprire de Sărbători',
      outlet: 'CSID',
      url: 'https://www.csid.ro/diete/dieta-si-nutritie/dr-drd-psih-costin-damasaru-ne-explica-de-ce-simtim-nevoia-sa-mancam-fara-oprire-de-sarbatori-20452999/',
      type: 'publicatie',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'The pandemic was a powerful incentive',
      outlet: 'Business Review',
      url: 'https://finand.ro/85461/br-interview-costin-damasaru-npe-center-the-pandemic-was-a-very-powerful-incentive-for-creating-efficient-procedures/',
      type: 'publicatie',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Top 100 Performeri în Sănătate (premiat)',
      outlet: 'EVZ + Gala Capital',
      url: 'https://evz.ro/gala-performerilor-in-medicina-costin-damasaru-veruvis-in-romania-se-poate-dezvolta-medicina-iar-noi-contribuim-la-asta.html',
      type: 'publicatie',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Cum a ajuns să-și controleze mintea (theXclusive feature)',
      outlet: 'Știrile Kanal D',
      url: 'https://www.stirilekanald.ro/o-experienta-de-viata-din-care-poti-invata-costin-damasaru-expert-in-neurostiinta-povesteste-la-in-oglinda-pe-canalul-de-youtube-thexclusive-cum-a-ajuns-sa-si-controleze-mintea-20257131',
      type: 'publicatie',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Tag autor (mențiuni multiple)',
      outlet: 'Wall-Street.ro',
      url: 'https://www.wall-street.ro/tag/costin-damasaru.html',
      type: 'publicatie',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },
    {
      title: '9 articole de opinie (autor)',
      outlet: 'Contributors.ro',
      url: 'https://www.contributors.ro/author/costin-damasaru/',
      type: 'publicatie',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },

    // ============================================================
    // RADIO (1 apariție)
    // ============================================================
    {
      title: 'Guerilla',
      outlet: 'Radio Guerrilla',
      url: 'https://www.youtube.com/watch?v=5zxHlih6428',
      type: 'radio',
      brand: 'veruvis',
      isMagazine: false,
      featured: false,
    },

    // ============================================================
    // EVENIMENTE (4 apariții)
    // ============================================================
    {
      title: 'I Love Failure — Moment Costin Dămășaru',
      outlet: 'I Love Failure',
      url: 'https://www.youtube.com/watch?v=g09bYnoR71Y',
      type: 'evenimente',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'EuroNews Romania @GoTech World',
      outlet: 'EuroNews Romania',
      url: 'https://www.facebook.com/ro.euronews/videos/933286555515283/?st=4JQbcQh3eiU',
      type: 'evenimente',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'Editura Herald la Gaudeamus',
      outlet: 'Gaudeamus',
      url: 'https://www.youtube.com/watch?v=GSKMZnq1HEw',
      type: 'evenimente',
      brand: 'costin',
      isMagazine: false,
      featured: false,
    },
    {
      title: 'TEDx Constanța',
      outlet: 'TEDx Constanța',
      url: 'https://www.youtube.com/watch?v=zsecrIL29ho',
      type: 'evenimente',
      brand: 'costin',
      isMagazine: false,
      featured: true,
    },
  ]

  await upsertList(strapi, 'api::press-mention.press-mention', items, 'url')
}
